pipeline {
    agent {
    node {
       label 'built-in'
       customWorkspace "/root/rps"	 
     }
     }

          stages {
		  
	    stage('CleanWorkspace'){
              steps {
              cleanWs()
            }
            }

	    stage ('gitclone') {
	      steps {
		sh "git clone https://github.com/shashi76/rock-paper-scissors.git"
		}	 
                }
					
              stage ('mvn build') {
		steps {
		  dir ("/root/rps/rock-paper-scissors/") {
		    sh "mvn clean"
	            sh "mvn install" 
		}	 
                }
         	}

	      stage ('tomcat stop') {
		steps {
		  dir ("/root/apache-tomcat-9.0.94/bin/") {
		    sh 'sh shutdown.sh'
	            sh 'rm -rf /root/apache-tomcat-9.0.94/webapps/rock-paper-scissors.war'		  
		}	 
                }
         	}
					
               stage ('deployment') {
                 steps {	
                   sh "cp -r /root/rps/rock-paper-scissors/target/rock-paper-scissors.war /root/apache-tomcat-9.0.94/webapps/"
                    }
                    }
				
	        stage ('start tomcat server') {
		  steps {
	          keepRunning {	
	          dir ("/root/apache-tomcat-9.0.94/bin/") {	
                    sh 'sh startup.sh'
		  }
                  }
		  }
		  }
		
            }	
}
